/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  Changyu Wang
 * Created: 2022-5-10
 */

INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STUFFORCUSTOMER)VALUES ('John', 'john@me.com', '456456', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Changyu', 'changyu@me.com', '87654656', 'aaa', 'staff');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Alva', 'alva@me.com', '786987669678', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Ben', 'ben@me.com', '12312345', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Chris', 'chris@me.com', '7658978656578', 'aaa', 'staff');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Tom', 'tom@me.com', '787564563', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Bob', 'bob@me.com', '4568756668575', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Jerry', 'jerry@me.com', '4563456678754', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Keith', 'keith@me.com', '45786758645', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Eddie', 'eddie@me.com', '4536453687', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Cobe', 'cobe@me.com', '11111111111', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Tank', 'tank@me.com', '123123123123', 'aaa', 'staff');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Elijah', 'elijah@me.com', '4864685465', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Gary', 'gary@me.com', '486956489564', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Hank', 'hank@me.com', '78964531', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Deepti', 'deepti@me.com', '13144446666', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Yunkai', 'yunkai@me.com', '14544444444', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Jack', 'jack@me.com', '12312345611', 'aaa', 'staff');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Bill', 'bill@me.com', '864531', 'aaa', 'clinet');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Sunny', 'unny@me.com', '5768432', 'aaa', 'client');
INSERT INTO GROUP35.USER_TABLE (FULLNAME, EMAIL, PHONENUMBER, PASSWORD, STAFFORCUSTOMER)VALUES ('Jobs', 'jobs@me.com', '5768432', 'aaa', 'client');